### ISSUE TITLE
The datasets link can't be available, can you provide other link?

### ISSUE THREAD

**Issue by kartherion** [chenchao666/JDDA-Master#2]
As the title.

**Comment by chenchao666** [comment]
Please find the dataset set here.


https://drive.google.com/open?id=167tVIBI2dVa0D18i6CiM-hicFJ3DJFzX
https://drive.google.com/open?id=1-OSkyh1Vzg_sxWJ6u4nvuQ3FRfKmZ-UF



ahucomputer@126.com
 
From: kartherion
Date: 2019-11-25 00:36
To: chenchao666/JDDA-Master
CC: Subscribed
Subject: [chenchao666/JDDA-Master] The datasets link can't be available, have other link? (#2)
As the title.
―

**Comment by kartherion** [comment]
They are available, thanks for your reply.
